### ISSUE TITLE
Current day LED flash

### ISSUE THREAD

**Issue by mfraser** [taylor-made/pihut-xmastree-advent#1]
Is it possible to modify the code so that the LED corresponding to today's date flickers?

**Comment by taylor-made** [comment]
Good idea!

You could do this by returning an alternating value from `createSource()`, like this:

```
def createSource(day):
 value = True
 while True:
  currentDay = datetime.date.today().day
  if day < currentDay:
   yield True
  elif day == currentDay:
   yield value
   value = not value
  else:
   yield False
```

You can then change the `source_delay` to whatever length of time you want the LED to flash, e.g. every 1 second.
